name: Docker Build & Deploy


on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'master'
        type: string
      remote_server:
        description: 'Remote server to deploy to'
        required: true
        type: string

env:
  DOCKERHUB_REPO: parity
  DOCKERFILE_PATH: ./docker/dockerfiles/polkadot/nginx.Dockerfile
  CONTAINER_NAME: polkadot-nginx
  REMOTE_USER: devops

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
      # Checkout the specified branch
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Print deployment info
      - name: Print deployment info
        run: |
          echo "Image built and pushed: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:${{ github.sha }}"
          echo "Target server: ${{ github.event.inputs.remote_server }}"

      - name: Set Docker image tag
        id: set_tag
        run: echo "image_tag=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Add SSH key to agent
        env:
          CICD_PRIVATE_KEY: ${{ secrets.CICD_PRIVATE_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          echo "$CICD_PRIVATE_KEY" | ssh-add -
      
      - name: Deploy to remote server
        run: |
          echo "Deploying image ${{ needs.build-and-push.outputs.image_tag }} to ${{ github.event.inputs.remote_server }}"
          ssh -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ github.event.inputs.remote_server }} "
            docker pull ${{ needs.build-and-push.outputs.image_tag }} &&
            docker stop ${{ env.CONTAINER_NAME }} || true &&
            docker rm ${{ env.CONTAINER_NAME }} || true &&
            docker run -d --name ${{ env.CONTAINER_NAME }} -p 80:80 ${{ needs.build-and-push.outputs.image_tag }}
          "



