name: Docker Build & Deploy


on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'master'
        type: string
      build-cmd:
        description: 'CI build command'
        required: true
        type: string
        default: 'cargo build --locked --release -p polkadot'
      remote_server:
        description: 'Remote server to deploy to'
        required: true
        type: string
        default: '145.239.2.149'

env:
  DOCKERHUB_USERNAME: chainsafeinfra
  DOCKERHUB_REPO: parity
  DOCKERFILE_PATH: ./docker/dockerfiles/polkadot/custom_polkadot_builder.Dockerfile
  CONTAINER_NAME: polkadot-nginx
  REMOTE_USER: devops

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
      # Checkout the specified branch
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      # Verify checkout TEMP
      - name: Verify branch checkout
        run: |
          echo "show disk" 
          df -h
          echo "Current branch and commit:"
          git status
          git log -1 --oneline
          echo "Directory contents:"
          ls -lah

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # Set Docker image tag
      - name: Set Docker image tag
        id: set_tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          # Replace slashes in branch name to avoid invalid tag names
          SAFE_BRANCH=$(echo "${{ github.event.inputs.branch }}" | tr '/' '-')
          TAG="${SAFE_BRANCH}-${SHORT_SHA}"
          echo "image_tag=${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:${TAG}" >> $GITHUB_OUTPUT

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ steps.set_tag.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VCS_REF=${{ github.ref }}
            POLKADOT_REPO=https://github.com/ChainSafe/polkadot-sdk.git
            POLKADOT_BRANCH=${{ github.event.inputs.branch }}
            CARGO_BUILD_CMD=${{ github.event.inputs.build-cmd }}


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CICD_PRIVATE_KEY }}

      # - name: Deploy to remote server
      #   run: |
      #     echo "Deploying image ${{ needs.build-and-push.outputs.image_tag }} to ${{ github.event.inputs.remote_server }}"
      #     ssh -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ github.event.inputs.remote_server }} "
      #       docker pull ${{ needs.build-and-push.outputs.image_tag }} &&
      #       docker stop ${{ env.CONTAINER_NAME }} || true &&
      #       docker rm ${{ env.CONTAINER_NAME }} || true &&
      #       docker run -d --name ${{ env.CONTAINER_NAME }} -p 8000:80 ${{ needs.build-and-push.outputs.image_tag }}
      #     "



